### PR TITLE
windows fixes

### PR DESCRIPTION
**Pull request by weltling**
With this patch the latest CLD release could be built on windows. That's almost about symbol import/export. Next release should be fine with this.

### CODE REVIEW

**Comment by lstrojny** [comment]
Sorry that it took me so long to react. Could you please adjust your PR to the latest version, that supports the latest upstream version of CLD.

**Comment by weltling** [comment]
np, hope to get to it soon )

**Comment by lstrojny** [comment]
Thank you! I would do it on my own, but I don’t have a Windows build environment set up, so it’s really hard to test those things.

**Comment by weltling** [comment]
With the last commits cld2 build works, I made some snapshots http://windows.php.net/downloads/pecl/snaps/cld/0.6.0-dev/ ... I've got some tests failing, but not completely. Almost on windows some longer text string is needed for the recognition. Not sure why.

**Pull request merged**
