### PR TITLE
Made normalized_score a double[3]

### PR DESCRIPTION
**Pull request by arnaud-lb**
This changes normalized_score variable to a double[3] since CompactLangDet::DetectLanguage apparently takes a double[3]. (I was seeing many INVALID_LANGUAGE returned from detect(), it turns out that CLD was overriding languages[0] when writing to (&normalized_score)[1].)

I've also included a change that return scores and percentages from from detect().

### CODE REVIEW

**Comment by lstrojny** [comment]
Thank you very much. Change looks fine. Could you add it to package.xml (feel free to add your name) and request the merge again?

**Comment by arnaud-lb** [comment]
Sure. Should I create a new version in the package.xml ?

**Comment by lstrojny** [comment]
No, just adding a note stating "CLD\detect() CLD\Detector::detectLanguage() now contains two new keys score and percentage" is enough

**Comment by arnaud-lb** [comment]
ok, done

**Comment by lstrojny** [comment]
Thanks!

**Pull request merged**
